name: macos ci

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: install dependencies
      run: brew install boost llvm coreutils
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: configure
      run: mkdir -p build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror -fsanitize=address,undefined -fno-omit-frame-pointer"  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ ..
    - name: run test harness
      run: cd build && ../scripts/test_all.sh -j8
